name: 002

on:
  push: 
    branches: ["002"]
  
  workflow_dispatch:


jobs:
  simple-print:
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        run: echo "hello world from demo"
