# This is a basic workflow to help you get started with Actions

name: 008

on:
  push:
    branches: [ "main" ,"008"]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      fruit: 
        description: "this is a fruit"
        type: string
        default: "apple"

jobs:
  inputs-job:
    runs-on: ubuntu-latest
    outputs:
      fruit_name: ${{ steps.step1.outputs.fruit }}
    steps:
      - uses: actions/checkout@v4
      - name: echo job
        run: echo "${{ inputs.fruit }}"
      - name: output job
        run: echo "fruit=${{ inputs.fruit }}" >> "$GITHUB_OUTPUT"

  output-job:
    needs: [inputs-job]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: echo output var
        run: echo ${{ needs.inputs-job.outputs.fruit_name }}
        
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: echo job
        run: echo "build job"

  deploy-dev01:
    needs: [build]
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: deploy job
        run: echo "this is deploy job"
        
  deploy-dev02:
    needs: [build]
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: deploy job
        run: echo "this is deploy job"
