
name: "007"

on:
  push:
    branches: [ "main" ,"007"]
  pull_request:
    branches: [ "main" ]
    

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      url: "https://jsonplaceholder.typicode.com/posts"
      post_number: ${{vars.NUMBER}}

    steps:
      - uses: actions/checkout@v4

      - name: echo variable
        run: echo ${{vars.NUMBER}}
      - name: echo secret
        run: |
              echo ${{secrets.NAME}} == 'dummy'
      - name: run the script
        run: sh getData.sh

