name: 009

on:
  push:
    branches: [ "main", "009" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  mvn-app-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        cd demo
        mvn clean install
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: java-app-jar
        path: demo/target/*

  mvn-unit-test:
    runs-on: ubuntu-latest
    needs: [mvn-app-build]

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run unit tests
      run: |
        cd demo
        mvn test
  docker-package:

    runs-on: ubuntu-latest
    needs: [mvn-unit-test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: ls
        run: ls -la

      # Step 2: Download artifact
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: java-app-jar
          path: demo/target/*
      - name: ls
        run: ls -la
      - name: Build the Docker image
        run: docker build . --file Dockerfile --build-arg JAR_FILE=java-app-jar/app.jar --tag demo-app:$(date +%s)
