name: 009

on:
  push:
    branches: [ "main","009" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  mvn-app-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
            cd demo
            mvn clean install
    - name: save artifacts
      with:
        name: build-artifacts
        path: demo/target/
  mvn-unit-test:
    runs-on: ubuntu-latest
    # needs: [mvn-app-build]
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: run tests
      run: |
            cd demo
            mvn test

