# This is a basic workflow to help you get started with Actions

name: 008

on:
  push:
    branches: [ "main" ,"008"]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      number: 
        description: "this is a lucky number"
        type: string
        default: '2'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: echo job
        run: echo "${{ inputs.number }}"
